#!/usr/bin/env bash
# phase5_backfill.sh — One-shot backfill of ~369 ES-missing files from audit_results_v3.
#
# USAGE:
#   bash phase5_backfill.sh [--dry-run] [--sleep SECONDS] [--max-files N]
#
# STATE FILES:
#   /APPBOX_DATA/storage/.translation-state/phase5_remaining.txt
#     — input worklist (one absolute media path per line)
#     — generated by: python3 phase5_gen_list.py > phase5_remaining.txt
#   /APPBOX_DATA/storage/.translation-state/phase5_done.txt
#     — append-only log of successfully translated paths
#   /APPBOX_DATA/storage/.translation-state/phase5_failed.txt
#     — append-only log of failed paths
#   /APPBOX_DATA/storage/.translation-state/phase5_status.txt
#     — current progress: <done>/<total> written every PROGRESS_EVERY files
#
# RESTART SAFETY:
#   On restart, already-done paths (from phase5_done.txt) are skipped.
#   flock ensures only one instance runs at a time.
#
# RATE LIMITING:
#   SLEEP_BETWEEN_FILES (default 30s) between each translated file.
#   Set to 0 for no sleep.
#
set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
readonly STATE_DIR="/APPBOX_DATA/storage/.translation-state"
readonly REMAINING_FILE="${STATE_DIR}/phase5_remaining.txt"
readonly DONE_FILE="${STATE_DIR}/phase5_done.txt"
readonly FAILED_FILE="${STATE_DIR}/phase5_failed.txt"
readonly STATUS_FILE="${STATE_DIR}/phase5_status.txt"
readonly LOCK_FILE="/tmp/phase5_backfill.lock"
readonly LOG_FILE="/config/berenstuff/automation/logs/phase5_backfill.log"
readonly PYTHONPATH_DIR="/config/berenstuff/automation/scripts"
readonly WORK_DIR="/config/berenstuff"
readonly ENV_FILE="/config/berenstuff/.env"

SLEEP_BETWEEN_FILES="${SLEEP_BETWEEN_FILES:-30}"
PROGRESS_EVERY="${PROGRESS_EVERY:-10}"
MAX_FILES="${MAX_FILES:-}"
DRY_RUN=0

# ── Arg parsing ───────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run)    DRY_RUN=1 ;;
        --sleep)      SLEEP_BETWEEN_FILES="${2:?--sleep requires a value}"; shift ;;
        --max-files)  MAX_FILES="${2:?--max-files requires a value}"; shift ;;
        *)            echo "Unknown arg: $1" >&2; exit 1 ;;
    esac
    shift
done

# ── Logging ───────────────────────────────────────────────────────────────────
log() { printf '%s [phase5] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*" | tee -a "$LOG_FILE"; }
die() { log "FATAL: $*"; exit 1; }

# ── Lock (flock fd 9) ─────────────────────────────────────────────────────────
exec 9>"$LOCK_FILE"
if ! flock -n 9; then
    echo "Another phase5_backfill instance is already running" >&2
    exit 1
fi

# ── Prerequisites ─────────────────────────────────────────────────────────────
[[ -f "$ENV_FILE" ]] || die "Missing env file: $ENV_FILE"
source "$ENV_FILE"

[[ -f "$REMAINING_FILE" ]] || die "Work list not found: $REMAINING_FILE
  Generate it first:
    python3 /config/berenstuff/automation/scripts/translation/phase5_gen_list.py"

OLLAMA_URL="${OLLAMA_BASE_URL:-http://127.0.0.1:11435}"
if ! curl -fsS --max-time 5 "${OLLAMA_URL}/api/tags" > /dev/null 2>&1; then
    die "Ollama unreachable at ${OLLAMA_URL} — is the WSL tunnel live?"
fi

# ── Load state ────────────────────────────────────────────────────────────────
touch "$DONE_FILE" "$FAILED_FILE"

declare -A done_set=()
while IFS= read -r path; do
    [[ -n "$path" ]] && done_set["$path"]=1
done < "$DONE_FILE"

mapfile -t worklist < "$REMAINING_FILE"
total="${#worklist[@]}"

[[ "$total" -eq 0 ]] && { log "Worklist is empty — nothing to do."; exit 0; }

# ── Main loop ─────────────────────────────────────────────────────────────────
done_count="${#done_set[@]}"
run_count=0
fail_count=0

log "=== Phase 5 Backfill START === worklist=$total already_done=$done_count dry_run=$DRY_RUN"

for media_path in "${worklist[@]}"; do
    [[ -z "$media_path" ]] && continue

    # Skip already done
    if [[ -n "${done_set[$media_path]+_}" ]]; then
        continue
    fi

    # Cap per run
    if [[ -n "$MAX_FILES" && "$MAX_FILES" -gt 0 && "$run_count" -ge "$MAX_FILES" ]]; then
        log "Reached --max-files $MAX_FILES for this run"
        break
    fi

    if [[ ! -f "$media_path" ]]; then
        log "SKIP (not on disk): $(basename "$media_path")"
        echo "$media_path" >> "$FAILED_FILE"
        fail_count=$((fail_count + 1))
        continue
    fi

    if [[ "$DRY_RUN" -eq 1 ]]; then
        log "DRY-RUN: $(basename "$media_path")"
        run_count=$((run_count + 1))
        continue
    fi

    log "TRANSLATING [$(( done_count + run_count + 1 ))/$total]: $(basename "$media_path")"

    output="$(cd "$WORK_DIR" && PYTHONPATH="$PYTHONPATH_DIR" \
        python3 -m translation.translator translate --file "$media_path" 2>&1)" || true

    if echo "$output" | grep -qE "Done: [1-9][0-9]* translated|All profile langs present"; then
        log "OK: $(basename "$media_path")"
        echo "$media_path" >> "$DONE_FILE"
        done_set["$media_path"]=1
        run_count=$((run_count + 1))
    elif echo "$output" | grep -q "No source SRT"; then
        log "NO_SOURCE: $(basename "$media_path")"
        echo "$media_path" >> "$FAILED_FILE"
        fail_count=$((fail_count + 1))
    elif echo "$output" | grep -qE "Ollama unreachable|Connection refused|OllamaUnavailable"; then
        log "ABORT: Ollama went away — stopping safely"
        break
    else
        tail_line="$(echo "$output" | grep -E 'ERROR|Done:|Traceback|failed' | tail -1)"
        log "FAIL: $(basename "$media_path") — ${tail_line:-unknown error}"
        echo "$media_path" >> "$FAILED_FILE"
        fail_count=$((fail_count + 1))
    fi

    # Progress report
    total_done=$(( done_count + run_count ))
    if (( run_count > 0 && (run_count % PROGRESS_EVERY) == 0 )); then
        printf '%s\n' "${total_done}/${total} done (${fail_count} failed this run)" | tee "$STATUS_FILE"
        log "PROGRESS: ${total_done}/${total} done, ${fail_count} failed"
    fi

    if [[ "${SLEEP_BETWEEN_FILES}" -gt 0 ]]; then
        sleep "$SLEEP_BETWEEN_FILES"
    fi
done

total_done=$(( done_count + run_count ))
printf '%s\n' "${total_done}/${total} done (${fail_count} failed this run)" | tee "$STATUS_FILE"
log "=== Phase 5 Backfill DONE === this_run=$run_count translated, ${fail_count} failed, ${total_done}/${total} total"
